# Generated by Django 6.0 on 2025-12-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("gpx_file", models.FileField(upload_to="gpx/")),
                (
                    "thumbnail_image",
                    models.ImageField(blank=True, upload_to="thumbnails/"),
                ),
                ("map_html", models.FileField(blank=True, upload_to="maps/")),
                ("distance_km", models.FloatField(default=0)),
                ("start_location", models.CharField(blank=True, max_length=300)),
                ("start_lat", models.FloatField(blank=True, null=True)),
                ("start_lon", models.FloatField(blank=True, null=True)),
                ("end_lat", models.FloatField(blank=True, null=True)),
                ("end_lon", models.FloatField(blank=True, null=True)),
                ("elevation_gain", models.FloatField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "share_token",
                    models.CharField(blank=True, max_length=32, unique=True),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="routes", to="routes.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
