# Generated by Django 6.0 on 2025-12-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="route_coordinates",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
