# Generated by Django 6.0 on 2025-12-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0002_route_route_coordinates"),
    ]

    operations = [
        migrations.CreateModel(
            name="StartPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Start Point",
                "verbose_name_plural": "Start Points",
                "ordering": ["name"],
            },
        ),
    ]
