# Generated by Django 6.0 on 2025-12-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0003_startpoint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="map_html",
        ),
    ]
