# Generated by Django 6.0 on 2025-12-18 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0004_remove_map_html_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="end_lat",
        ),
        migrations.RemoveField(
            model_name="route",
            name="end_lon",
        ),
    ]
